dist: trusty

language: node_js
node_js:
  - 8

jobs:
  include:
    - name: "windows"
      os: windows
      before_script:
        - npm run bootstrap
      script:
        - npm test
    - name: "linux"
      os: linux
      before_script:
        - npm run bootstrap
      script:
        - npm test
    - name: "osx"
      os: osx
      before_script:
        - npm run bootstrap
      script:
        - npm test
