
# -----------  Agents  -----------

[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
key_file = "holo_tester.key"

# -----------  DNA  -----------


[[dnas]]
id = "event_dna"
file = "dna/events-goer-4000.hcpkg"
hash = "Qm328wyq38924y"

[[instances]]
id = "events-goer-4000"
dna = "event_dna"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "events-goer-4000"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3001
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
n3h_path = "n3h"
n3h_persistence_path = "./"
bootstrap_nodes = ["/ip4/192.168.1.111/tcp/62071/ipfs/QmYj6uBjj9ET4rXGumE3dREAfVbWaY1skeLrQPkuy9tWuj"]

# -----------  Networking instructions  -----------

# To get networking running requires the following steps:
# - run `cd n3h && npm install && npm run boostrap && cd ..`

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above
